services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - laravel_net

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - laravel_net

  db:
    image: postgres:17
    container_name: laravel_db
    restart: always
    environment:
      POSTGRES_DB: db_csc
      POSTGRES_USER: cikampekswimming
      POSTGRES_PASSWORD: "123456"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: bridge

volumes:
  db_data: